name: CI Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 4 * * *'
      
     

jobs:
  ci-seg:
    runs-on: ubuntu-latest
  
    steps:
    - name : 'Checkout repo'
      uses: actions/checkout@v2.4.2

    - name : 'Setup Python'
      uses: actions/setup-python@v4
      if: steps.training-pipeline-change.outputs.src == 'true'
      with:
        python-version: '3.8'
        
    - name: 'Install required  packages'
     
      run: |
        pip install -r requirements.txt
