# This is a basic workflow to help you get started with Actions

name: CI Pipeline

on:
  push:
    branches:
      - main
      
     

jobs:
  ci-seg:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2.4.2

   
    - uses: actions/setup-python@v4
      if: steps.training-pipeline-change.outputs.src == 'true'
      with:
        python-version: '3.8'
        
    - name: 'Install required  packages'
     
      run: |
        pip install -r requirements.txt
